### ISSUE TITLE
Add APK delete capability

### ISSUE THREAD

**Issue by wags1** [un-linked/unlinked#10]
Add a manual delete capability from within the app that just deletes the APK's or a prompt to delete ala what Downloader does.

**Comment by dikodahan** [comment]
Filelinked automatically deleted all downloaded APK files upon exit/launch. This was a very nice feature to avoid running out of space on these very low mem devices.

**Comment by wags1** [comment]
> Filelinked automatically deleted all downloaded APK files upon exit/launch. This was a very nice feature to avoid running out of space on these very low mem devices.

Actually Filelinked had a toggle setting that would make it do that or not. It also had a manual apk delete button.

**Comment by wags1** [comment]
Feature now exists. Thanks!
