### ISSUE TITLE
[Bug] After installing an app, it keeps asking to install the app again.

### ISSUE THREAD

**Issue by mo123** [un-linked/unlinked#13]
The is a loop when you launch an app and install it, when installation is complete and you press back it asks you to install the app again.

**Comment by mo123** [comment]
I hope this bug can be fixed for the AndroidTV version.

**Comment by dikodahan** [comment]
I am experiencing the same issue on Android TV version 10 as well.
No issues on Fire TV, works as expected.

**Comment by mo123** [comment]
Yes, AndroidTV 10.
Somehow it doesn't think an app is installed and tries to install it again.
Maybe it's a problem with scoped storage or new permissions used in Android 10 that didn't exist in older AndroidTV OS's.

On AndroidTV 9 I didn't get this problem and apps only installed once.

**Comment by dikodahan** [comment]
@un-linked any updates on this bug?
This is quite an annoying issue. Appreciate any solution!

**Comment by dikodahan** [comment]
Updates please?
Has this project been abandoned? Have not seen any progress made on many of the open items. That would indeed be unfortunate. This platform is (hopefully not was...) extremely promising in it's feature and function set!

**Comment by un-linked** [comment]
This has been fixed in today's update.
