### ISSUE TITLE
[Feature Request] To scrape a link on a site and automatically open it to get a direct link

### ISSUE THREAD

**Issue by mo123** [un-linked/unlinked#22]
Would be great if a link on a site eg. link being generated by pressing a button can be automatically done to get the final direct download link that is dynamic.

Lots of streaming apps scrape video hosting sites to get a link and then open the link to get the final direct video link to play, maybe something similar can be done for download links to get direct links?

This will open up the possibility to use other file hosts like Mediafire that provide lots more storage and is faster than Dropbox and archive.org Eg. Mediafire links get direct links after you press on the download button but these direct links only last a few hours and then new random direct links are generated again if you press download, they are dynamic and not static.

**Comment by un-linked** [comment]
- This is beyond the scope of this project.
- Download experience for users very inconsistent. 
- Publishers will have hard time keeping track of their files.
