### ISSUE TITLE
[Bug] The Android APP fails to Download Big Files

### ISSUE THREAD

**Issue by mo123** [un-linked/unlinked#23]
The Android app fails to download big apps(100-200MB) from eg. archive.org.
Apps to to eg. 40% and fail, you can only redownload an app, there is no resume support.
When using the website on a PC or Android device then files download correctly since it uses Android's built-in downloader that also supports resume.

Please improve the app's built-in downloader for big files to not fail and also add download resume, pause support.

**Comment by un-linked** [comment]
What device are you using? How much ram does it have?

**Comment by mo123** [comment]
Rockchip RK3399, 4GB RAM, 32GB Storage, AndroidTV 10.

Big Downloads from archive.org don't finish and fail midway on AndroidTV 10 using the tv layout of the Unlinked app.
App sizes downloaded are between 50-200MB.
If using the phone app layout on a phone with Android 10, the downloads use Android's built-in downloader and finishes correctly.
Downloads from Dropbox finish correctly and can install on AndroidTV 10 but then ask to install the app 3 times.
Perhaps these 2 AndroidTV 10 bugs are related?
On AndroidTV 9 on the same device, using the tv layout of the Unlinked app, apps download correctly from archive.org but slowly.
