### ISSUE TITLE
After installation from any category сursor jumps back to "All files" category

### ISSUE THREAD

**Issue by samsmotri** [un-linked/unlinked#28]
Unlinked on Android TV

In the new version of unlinked after installing the application from some category, the cursor jumps to the main category "All files". This is very inconvenient when installing multiple applications from the same category. The cursor should remain on the application that was currently installed.
Please return it as it was in the previous version or make an option in the settings to jump to the main category or stay up to date.

**Comment by dikodahan** [comment]
+1 on this one!
