### ISSUE TITLE
[Feature Request] Potential features to further enhance Unlinked 

### ISSUE THREAD

**Issue by dikodahan** [un-linked/unlinked#3]
* After adding your first library, move the add library to the bottom of the libraries to avoid it being first one to show up as most likely you are already set with your favorite libraries.
* Add an option to assign a logo icon for your library instead of the default folder icon.
* Add an option to libraries up/down in the order of appearance (could be another option when you long press the OK button, above the remove library option).

**Comment by un-linked** [comment]
Please make separate issues for each request.
