### ISSUE TITLE
Host seems to be down Nov 20,2024

### ISSUE THREAD

**Issue by newtechevo** [un-linked/unlinked#46]
host seems to be down nov 20, 2023

**Comment by chris070475** [comment]
Unlinked unactive as always

**Comment by newtechevo** [comment]
Still down.

**Comment by chris070475** [comment]
Yep, problem is he is not active

**Comment by Zippojones007** [comment]
Unlinked.link server is down. Use Downloader code 867976

**Comment by chris070475** [comment]
Hi sir website and app are down since yesterday
