### ISSUE TITLE
[Feature Request] Add the ability to move files between your libraries

### ISSUE THREAD

**Issue by dikodahan** [un-linked/unlinked#8]
Very useful if you're managing multiple libraries and as features evolve you may way to consider consolidating libraries into one.

**Comment by un-linked** [comment]
Each library is a separate container. You may use the json import facility to import files around.

**Comment by dikodahan** [comment]
Fair enough.
Worth pointing out though that having to write the complete description for each file in a Json file VS just having a Move file option is not as simple and elegant if you want to move around multiple files.
Maybe this is a backlog feature...

**Comment by un-linked** [comment]
Each library resides in a separate encrypted container. It is technically impossible to reference the same file from different lib. May add a "Clone this file" to a library option in the future.
